//SCHOOL TYPES
export const FETCH_SCHOOLS = 'FETCH_SCHOOLS'
export const SELECT_SCHOOL = 'SELECT_SCHOOL'

//TERM TYPES
export const FETCH_TERMS = 'FETCH_TERMS'
export const SELECT_TERM = 'SELECT_TERM'

//MAJOR TYPES
export const FETCH_MAJORS = 'FETCH_MAJORS'
export const EMPTY_MAJORS = 'EMPTY_MAJORS'

//COURSE ACTIONS
export const ADD_COURSE = 'ADD_COURSE'
export const REMOVE_ALL_COURSES = 'REMOVE_ALL_COURSES'
export const EDIT_COURSE = 'EDIT_COURSE'
export const REMOVE_COURSE = 'REMOVE_COURSE'
